### ISSUE TITLE
tcl-tk: Can't install Centos 6.6

### ISSUE THREAD

**Issue by mistydemeo** [Linuxbrew/legacy-linuxbrew#458]
_From @phorust on June 26, 2015 1:17_

I'm following [this guide](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation) to get a clean brew install so I can get neovim with python support working on Centos 6.6 while working behind a proxy on a system without root (kind of). (which has taken me so long I've considered stopping my use of vim completely, no joke).

Anyhow, I'm getting the following error

```
==> Installing git dependency: homebrew/dupes/tcl-tk
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tcl8.6.4-src.tar.
Already downloaded: /home/phorust/.cache/Homebrew/tcl-tk-8.6.4.tar.gz
==> Patching
patching file pkgs/sqlite3.8.8.3/generic/sqlite3.c
==> ./configure --prefix=/home/phorust/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/home/phor
==> make
==> make install
==> make install-private-headers
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.4/tk8.6.4-src.tar.g
Already downloaded: /home/phorust/.cache/Homebrew/tcl-tk--tk-8.6.4.tar.gz
==> ./configure --prefix=/home/phorust/.linuxbrew/Cellar/tcl-tk/8.6.4 --mandir=/home/phor
==> make TK_LIBRARY=/home/phorust/.linuxbrew/Cellar/tcl-tk/8.6.4/lib
/tmp/tcl-tk--tk20150625-2353807-j99v3m/tk8.6.4/unix/../generic/tkBind.c: At top level:
/tmp/tcl-tk--tk20150625-2353807-j99v3m/tk8.6.4/unix/../generic/tkBind.c:4199: error: expec
ted ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘TkStringToKeysym’
/tmp/tcl-tk--tk20150625-2353807-j99v3m/tk8.6.4/unix/../generic/tkBind.c:4238: error: expec
ted ‘)’ before ‘keysym’
/tmp/tcl-tk--tk20150625-2353807-j99v3m/tk8.6.4/unix/../generic/tkBind.c:4270: error: expec
ted ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
make: *** [tkBind.o] Error 1
```

_Copied from original issue: Homebrew/homebrew-dupes#481_

**Comment by mistydemeo** [comment]
Can you provide the output of `brew gist-logs tcl-tk` please?

**Comment by mistydemeo** [comment]
_From @phorust on June 26, 2015 2:27_

Unfortunately looks like I'm running into another error
```
~  ➜  https_proxy=proxyout:8080 brew gist-logs tcl-tk
Error: getaddrinfo: Name or service not known
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `open'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:67:in `timeout'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:852:in `start'
/home/phorust/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1369:in `request'
/home/phorust/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:115:in `post'
/home/phorust/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/home/phorust/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/home/phorust/.linuxbrew/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/home/phorust/.linuxbrew/Library/brew.rb:140:in `<main>'
```

**Comment by mistydemeo** [comment]
Can you upload all of the logs from `~/.cache/Homebrew/Logs/tcl-tk` to gist.github.com and provide the link? Also provide your `brew --config` and `brew doctor` output, please.

**Comment by mistydemeo** [comment]
Ping.

**Comment by mistydemeo** [comment]
_From @phorust on June 30, 2015 22:23_

Possibly related issue: Homebrew/homebrew/issues/41132

Logs from `~/.cache/Homebrew/Logs/tcl-tk`
https://gist.github.com/phorust/6c64323dee459c45739a
https://gist.github.com/phorust/4f637440595a119b4523
https://gist.github.com/phorust/676a823e1c454c94c8d5
https://gist.github.com/phorust/d7ae9fbf27194fdd2e4b
https://gist.github.com/phorust/47d8aef9db79d4508b88
https://gist.github.com/phorust/1651715c1592843640a7

Output of `brew --config`:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: c30e5ce25b182daffdb3e1123dc1a6652019cc27
Last commit: 3 hours ago
HOMEBREW_PREFIX: /home/phorust/.linuxbrew
HOMEBREW_CELLAR: /home/phorust/.linuxbrew/Cellar
CPU: 32-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 2.1.0 => /home/phorust/.rvm/rubies/ruby-2.1.0/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/bin/python
Ruby: /home/phorust/.rvm/rubies/ruby-2.1.0/bin/ruby
Java: 1.8.0_25
```

Output of `brew doctor`:
```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /opt/local/bin/proxyout-config
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/libgimli.h
    /usr/local/include/libavutil/aes.h
    /usr/local/include/libavutil/bswap.h
    /usr/local/include/libavutil/pixfmt.h
    /usr/local/include/libavutil/log.h
    /usr/local/include/libavutil/imgutils.h
    /usr/local/include/libavutil/intreadwrite.h
    /usr/local/include/libavutil/avutil.h
    /usr/local/include/libavutil/dict.h
    /usr/local/include/libavutil/file.h
    /usr/local/include/libavutil/samplefmt.h
    /usr/local/include/libavutil/eval.h
    /usr/local/include/libavutil/sha.h
    /usr/local/include/libavutil/error.h
    /usr/local/include/libavutil/common.h
    /usr/local/include/libavutil/random_seed.h
    /usr/local/include/libavutil/intfloat_readwrite.h
    /usr/local/include/libavutil/crc.h
    /usr/local/include/libavutil/md5.h
    /usr/local/include/libavutil/base64.h
    /usr/local/include/libavutil/pixdesc.h
    /usr/local/include/libavutil/avstring.h
    /usr/local/include/libavutil/lfg.h
    /usr/local/include/libavutil/rational.h
    /usr/local/include/libavutil/avassert.h
    /usr/local/include/libavutil/attributes.h
    /usr/local/include/libavutil/parseutils.h
    /usr/local/include/libavutil/avconfig.h
    /usr/local/include/libavutil/cpu.h
    /usr/local/include/libavutil/mathematics.h
    /usr/local/include/libavutil/fifo.h
    /usr/local/include/libavutil/intfloat.h
    /usr/local/include/libavutil/adler32.h
    /usr/local/include/libavutil/mem.h
    /usr/local/include/libavutil/lzo.h
    /usr/local/include/libavutil/opt.h
    /usr/local/include/libavutil/audioconvert.h
    /usr/local/include/clapack.h
    /usr/local/include/evdns.h
    /usr/local/include/cblas.h
    /usr/local/include/event2/rpc_compat.h
    /usr/local/include/event2/bufferevent_compat.h
    /usr/local/include/event2/bufferevent_ssl.h
    /usr/local/include/event2/listener.h
    /usr/local/include/event2/rpc.h
    /usr/local/include/event2/bufferevent.h
    /usr/local/include/event2/buffer_compat.h
    /usr/local/include/event2/event_compat.h
    /usr/local/include/event2/buffer.h
    /usr/local/include/event2/http_struct.h
    /usr/local/include/event2/dns_struct.h
    /usr/local/include/event2/event.h
    /usr/local/include/event2/thread.h
    /usr/local/include/event2/dns_compat.h
    /usr/local/include/event2/event_struct.h
    /usr/local/include/event2/tag_compat.h
    /usr/local/include/event2/dns.h
    /usr/local/include/event2/bufferevent_struct.h
    /usr/local/include/event2/keyvalq_struct.h
    /usr/local/include/event2/rpc_struct.h
    /usr/local/include/event2/http.h
    /usr/local/include/event2/tag.h
    /usr/local/include/event2/http_compat.h
    /usr/local/include/event2/util.h
    /usr/local/include/event2/event-config.h
    /usr/local/include/atlas/atlas_dGetNB_gerqf.h
    /usr/local/include/atlas/atlas_zmvn_L2.h
    /usr/local/include/atlas/atlas_dGetNB_geqlf.h
    /usr/local/include/atlas/atlas_cNCmm.h
    /usr/local/include/atlas/atlas_sr2kernels.h
    /usr/local/include/atlas/atlas_dr1_L2.h
    /usr/local/include/atlas/atlas_cr2_L2.h
    /usr/local/include/atlas/atlas_cmvt_L2.h
    /usr/local/include/atlas/atlas_dtGetNB_gelqf.h
    /usr/local/include/atlas/atlas_cr1_L2.h
    /usr/local/include/atlas/atlas_ssyr2.h
    /usr/local/include/atlas/atlas_smvn.h
    /usr/local/include/atlas/atlas_taffinity.h
    /usr/local/include/atlas/atlas_dsyr2.h
    /usr/local/include/atlas/atlas_zmvn.h
    /usr/local/include/atlas/atlas_csyr.h
    /usr/local/include/atlas/atlas_cGetNB_gerqf.h
    /usr/local/include/atlas/atlas_ssyrNX.h
    /usr/local/include/atlas/atlas_zsyr.h
    /usr/local/include/atlas/atlas_dr1_L1.h
    /usr/local/include/atlas/atlas_buildinfo.h
    /usr/local/include/atlas/atlas_zmvt_L2.h
    /usr/local/include/atlas/atlas_zr2_L1.h
    /usr/local/include/atlas/atlas_dsysinfo.h
    /usr/local/include/atlas/atlas_smvt_L2.h
    /usr/local/include/atlas/atlas_dsyrNX.h
    /usr/local/include/atlas/atlas_zmvtkernels.h
    /usr/local/include/atlas/atlas_cmvt.h
    /usr/local/include/atlas/atlas_dmvn_L1.h
    /usr/local/include/atlas/atlas_ztGetNB_gerqf.h
    /usr/local/include/atlas/atlas_zGetNB_gerqf.h
    /usr/local/include/atlas/atlas_zsyr_L1.h
    /usr/local/include/atlas/atlas_zr1_L2.h
    /usr/local/include/atlas/atlas_dsyr2_L2.h
    /usr/local/include/atlas/cmm.h
    /usr/local/include/atlas/atlas_dtrsmXover.h
    /usr/local/include/atlas/atlas_zGetNB_geqlf.h
    /usr/local/include/atlas/atlas_zr1kernels.h
    /usr/local/include/atlas/atlas_dsyr_L1.h
    /usr/local/include/atlas/atlas_cGetNB_gelqf.h
    /usr/local/include/atlas/atlas_ztGetNB_gelqf.h
    /usr/local/include/atlas/atlas_cacheedge.h
    /usr/local/include/atlas/atlas_dsyr2_L1.h
    /usr/local/include/atlas/atlas_ssyr2NX.h
    /usr/local/include/atlas/atlas_tsumm.h
    /usr/local/include/atlas/atlas_smvn_L2.h
    /usr/local/include/atlas/atlas_dmvt_L1.h
    /usr/local/include/atlas/atlas_csyr_L1.h
    /usr/local/include/atlas/atlas_ztrsmXover.h
    /usr/local/include/atlas/atlas_zher2_L1.h
    /usr/local/include/atlas/atlas_sGetNB_gerqf.h
    /usr/local/include/atlas/atlas_zsyr2NX.h
    /usr/local/include/atlas/atlas_cher2.h
    /usr/local/include/atlas/atlas_ztGetNB_geqlf.h
    /usr/local/include/atlas/atlas_ctGetNB_geqlf.h
    /usr/local/include/atlas/atlas_sr2_L2.h
    /usr/local/include/atlas/atlas_slamch.h
    /usr/local/include/atlas/atlas_csyr2NX.h
    /usr/local/include/atlas/atlas_csNKB.h
    /usr/local/include/atlas/atlas_dsyr2NX.h
    /usr/local/include/atlas/atlas_cr1.h
    /usr/local/include/atlas/atlas_cGetNB_geqrf.h
    /usr/local/include/atlas/atlas_sGetNB_geqlf.h
    /usr/local/include/atlas/atlas_stGetNB_geqrf.h
    /usr/local/include/atlas/dmm.h
    /usr/local/include/atlas/atlas_sr1.h
    /usr/local/include/atlas/zmm.h
    /usr/local/include/atlas/atlas_sr1_L1.h
    /usr/local/include/atlas/atlas_dtGetNB_geqrf.h
    /usr/local/include/atlas/atlas_cmvnkernels.h
    /usr/local/include/atlas/atlas_dr2kernels.h
    /usr/local/include/atlas/atlas_dsyr.h
    /usr/local/include/atlas/atlas_stGetNB_gelqf.h
    /usr/local/include/atlas/atlas_stGetNB_gerqf.h
    /usr/local/include/atlas/atlas_cr2.h
    /usr/local/include/atlas/atlas_smvt_L1.h
    /usr/local/include/atlas/atlas_dr1kernels.h
    /usr/local/include/atlas/atlas_zmvnkernels.h
    /usr/local/include/atlas/atlas_zr2_L2.h
    /usr/local/include/atlas/atlas_cr2kernels.h
    /usr/local/include/atlas/atlas_smvtkernels.h
    /usr/local/include/atlas/atlas_dr1.h
    /usr/local/include/atlas/atlas_cmvn_L1.h
    /usr/local/include/atlas/atlas_tcacheedge.h
    /usr/local/include/atlas/atlas_cmvn.h
    /usr/local/include/atlas/atlas_zmvn_L1.h
    /usr/local/include/atlas/atlas_zr2kernels.h
    /usr/local/include/atlas/atlas_dlamch.h
    /usr/local/include/atlas/atlas_zr1_L1.h
    /usr/local/include/atlas/atlas_ssyr_L1.h
    /usr/local/include/atlas/atlas_dsyr_L2.h
    /usr/local/include/atlas/sXover.h
    /usr/local/include/atlas/atlas_zr1.h
    /usr/local/include/atlas/atlas_stGetNB_geqlf.h
    /usr/local/include/atlas/atlas_zGetNB_gelqf.h
    /usr/local/include/atlas/atlas_cr2_L1.h
    /usr/local/include/atlas/atlas_dmvn.h
    /usr/local/include/atlas/atlas_sr1_L2.h
    /usr/local/include/atlas/atlas_csyr_L2.h
    /usr/local/include/atlas/smm.h
    /usr/local/include/atlas/atlas_zdNKB.h
    /usr/local/include/atlas/dXover.h
    /usr/local/include/atlas/atlas_dmvt_L2.h
    /usr/local/include/atlas/atlas_sr1kernels.h
    /usr/local/include/atlas/atlas_dr2_L1.h
    /usr/local/include/atlas/atlas_zher2.h
    /usr/local/include/atlas/atlas_sNCmm.h
    /usr/local/include/atlas/atlas_ctGetNB_gerqf.h
    /usr/local/include/atlas/atlas_cmvt_L1.h
    /usr/local/include/atlas/atlas_ssyr2_L1.h
    /usr/local/include/atlas/atlas_cher2_L1.h
    /usr/local/include/atlas/atlas_dr2.h
    /usr/local/include/atlas/atlas_dGetNB_gelqf.h
    /usr/local/include/atlas/atlas_dr2_L2.h
    /usr/local/include/atlas/atlas_cher2_L2.h
    /usr/local/include/atlas/atlas_zGetNB_geqrf.h
    /usr/local/include/atlas/atlas_zher2_L2.h
    /usr/local/include/atlas/atlas_sGetNB_gelqf.h
    /usr/local/include/atlas/atlas_dtGetNB_geqlf.h
    /usr/local/include/atlas/atlas_cmvn_L2.h
    /usr/local/include/atlas/atlas_csysinfo.h
    /usr/local/include/atlas/atlas_smvnkernels.h
    /usr/local/include/atlas/atlas_cr1kernels.h
    /usr/local/include/atlas/atlas_cr1_L1.h
    /usr/local/include/atlas/atlas_ssyr2_L2.h
    /usr/local/include/atlas/atlas_sGetNB_geqrf.h
    /usr/local/include/atlas/atlas_zmvt.h
    /usr/local/include/atlas/atlas_ctGetNB_gelqf.h
    /usr/local/include/atlas/atlas_smvn_L1.h
    /usr/local/include/atlas/atlas_strsmXover.h
    /usr/local/include/atlas/atlas_ztGetNB_geqrf.h
    /usr/local/include/atlas/atlas_smvt.h
    /usr/local/include/atlas/atlas_dmvt.h
    /usr/local/include/atlas/atlas_ssyr.h
    /usr/local/include/atlas/atlas_dNCmm.h
    /usr/local/include/atlas/atlas_zsysinfo.h
    /usr/local/include/atlas/atlas_zr2.h
    /usr/local/include/atlas/atlas_zmvt_L1.h
    /usr/local/include/atlas/atlas_ctGetNB_geqrf.h
    /usr/local/include/atlas/atlas_ssysinfo.h
    /usr/local/include/atlas/atlas_sr2.h
    /usr/local/include/atlas/atlas_ssyr_L2.h
    /usr/local/include/atlas/atlas_ctrsmXover.h
    /usr/local/include/atlas/atlas_trsmNB.h
    /usr/local/include/atlas/atlas_zsyrNX.h
    /usr/local/include/atlas/atlas_zsyr_L2.h
    /usr/local/include/atlas/atlas_dmvtkernels.h
    /usr/local/include/atlas/atlas_cmvtkernels.h
    /usr/local/include/atlas/atlas_csyrNX.h
    /usr/local/include/atlas/atlas_type.h
    /usr/local/include/atlas/atlas_sr2_L1.h
    /usr/local/include/atlas/atlas_pthreads.h
    /usr/local/include/atlas/atlas_dmvn_L2.h
    /usr/local/include/atlas/atlas_dGetNB_geqrf.h
    /usr/local/include/atlas/atlas_dmvnkernels.h
    /usr/local/include/atlas/atlas_cGetNB_geqlf.h
    /usr/local/include/atlas/atlas_dtGetNB_gerqf.h
    /usr/local/include/atlas/zXover.h
    /usr/local/include/atlas/atlas_zNCmm.h
    /usr/local/include/atlas/cXover.h
    /usr/local/include/libswresample/swresample.h
    /usr/local/include/event.h
    /usr/local/include/evhttp.h
    /usr/local/include/libavdevice/avdevice.h
    /usr/local/include/libavcodec/vaapi.h
    /usr/local/include/libavcodec/vda.h
    /usr/local/include/libavcodec/vdpau.h
    /usr/local/include/libavcodec/dxva2.h
    /usr/local/include/libavcodec/avfft.h
    /usr/local/include/libavcodec/xvmc.h
    /usr/local/include/libavcodec/version.h
    /usr/local/include/libavcodec/avcodec.h
    /usr/local/include/libavcodec/opt.h
    /usr/local/include/libavfilter/avfilter.h
    /usr/local/include/libavfilter/vsrc_buffer.h
    /usr/local/include/libavfilter/avfiltergraph.h
    /usr/local/include/libavfilter/buffersink.h
    /usr/local/include/libavfilter/version.h
    /usr/local/include/libavfilter/avcodec.h
    /usr/local/include/libgimli_ana.h
    /usr/local/include/libavformat/avio.h
    /usr/local/include/libavformat/avformat.h
    /usr/local/include/libavformat/version.h
    /usr/local/include/evrpc.h
    /usr/local/include/libswscale/swscale.h
    /usr/local/include/evutil.h
Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libevent_pthreads.la
    /usr/local/lib/libevent_extra.la
    /usr/local/lib/libevent_core.la
    /usr/local/lib/libevent_openssl.la
    /usr/local/lib/libevent.la
Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/libevent.pc
    /usr/local/lib/pkgconfig/libavutil.pc
    /usr/local/lib/pkgconfig/libavformat.pc
    /usr/local/lib/pkgconfig/libevent_pthreads.pc
    /usr/local/lib/pkgconfig/libavdevice.pc
    /usr/local/lib/pkgconfig/libavcodec.pc
    /usr/local/lib/pkgconfig/libswscale.pc
    /usr/local/lib/pkgconfig/libswresample.pc
    /usr/local/lib/pkgconfig/libevent_openssl.pc
    /usr/local/lib/pkgconfig/libavfilter.pc
Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libf77blas.a
    /usr/local/lib/liblapack.a
    /usr/local/lib/libswscale.a
    /usr/local/lib/libavutil.a
    /usr/local/lib/libevent.a
    /usr/local/lib/libavformat.a
    /usr/local/lib/libswresample.a
    /usr/local/lib/libevent_pthreads.a
    /usr/local/lib/libcblas.a
    /usr/local/lib/libavfilter.a
    /usr/local/lib/libptcblas.a
    /usr/local/lib/libevent_core.a
    /usr/local/lib/libatlas.a
    /usr/local/lib/libevent_openssl.a
    /usr/local/lib/libevent_extra.a
    /usr/local/lib/libavdevice.a
    /usr/local/lib/libptf77blas.a
    /usr/local/lib/libavcodec.a




Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl http://github.com


```

**Comment by sjackman** [comment]
You can safely skip installing `tcl-tk`. Instead install `git` without Tk support.
```sh
brew install git --with-brewed-curl --with-brewed-openssl --without-tcl-tk
```
See https://github.com/sjackman/docker-linuxbrew/blob/master/linuxbrew-standalone/Dockerfile

**Comment by sjackman** [comment]
@mistydemeo What script did you use to move this issue? That's a neat trick.

**Comment by saketkc** [comment]
@sjackman I think it is this: https://github.com/google/github-issue-mover

**Comment by sjackman** [comment]
Thanks, Saket. That's super useful.

**Comment by phorust** [comment]
Installing git without tcl-tk support did the trick, and I moved on to the next step of the Standalone Installation, and now I'm having trouble with `brew install coreutils`:

```
==> Downloading http://ftpmirror.gnu.org/coreutils/coreutils-8.23.tar.xz
Already downloaded: /home/phorust/.cache/Homebrew/coreutils-8.23.tar.xz
==> Patching
patching file Makefile.in
==> ./configure --prefix=/home/phorust/.linuxbrew/Cellar/coreutils/8.23_1 --program-prefix=g --without-gmp
==> make install
make[2]: *** [man/cp.1] Error 127
make[2]: Leaving directory `/tmp/coreutils20150701-270170-1ozqv4/coreutils-8.23'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/coreutils20150701-270170-1ozqv4/coreutils-8.23'
make: *** [install] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```

**Comment by sjackman** [comment]
Please report `brew gist-logs coreutils`

**Comment by phorust** [comment]
Similar problems to above where the proxy env vars aren't being used:
```
~  ➜ https_proxy=http://proxyout:8080 brew gist-logs coreutils
22:47:03 libtsocks(540725): Error 101 attempting to connect to SOCKS server (Network is unreachable)
Error: Network is unreachable - connect(2) for "api.github.com" port 443
```
I have http_proxy, HTTP_PROXY, https_proxy, and HTTPS_PROXY all set to http://proxyout:8080

**Comment by sjackman** [comment]
Yes, please.
