### ISSUE TITLE
node  failed to build on RHEL 6.7

### ISSUE THREAD

**Issue by typekpb** [Linuxbrew/legacy-linuxbrew#686]
logs by `brew gist-logs node`: https://gist.github.com/anonymous/9b768eca929eb0922372

**Comment by sjackman** [comment]
I'm on vacation until the new year. Please bump this thread after then. Sorry for the delay.

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/9b768eca929eb0922372#file-01-configure-L19
`ImportError: cannot import name urlencode`

**Comment by sjackman** [comment]
I'm able to install `node` 5.4.0 without any errors with a small patch that I made today. Can you try again and report back?

**Comment by sjackman** [comment]
Since the error message that you're seeing is related to Python, you may want to see if `brew install python` resolves your issue.

**Comment by rwhogg** [comment]
Closing this issue as it is unreproducible.
